//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public int idAplicacion { get; set; }
        public Nullable<int> idCurriculum { get; set; }
        public Nullable<int> idOfertaEmpleo { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual OfertaEmpleo OfertaEmpleo { get; set; }
    }
}
